name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker images
      run: |
        docker build ./api/ -t "${{ secrets.siwakornsupareak }}/app1-api:latest"
        docker build ./front/ -t "${{ secrets.siwakornsupareak }}/app1-frontend:latest"

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.Buffon.bf@27 }}" | docker login -u "${{ secrets.siwakornsupareak }}" --password-stdin

    - name: Push images to Docker Hub
      run: |
        docker push "${{ secrets.siwakornsupareak }}/app1-api:latest"
        docker push "${{ secrets.siwakornsupareak }}/app1-frontend:latest"
